---
title: "STAT585_Lab2"
author: "Xin Zhang"
date: "2/20/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(ggspatial)
library(tidyverse)
```

plot the original plot
```{r}
p <- ggplot() +
  geom_sf(data = read_sf("data/ME-GIS/Coastline2.shp"), 
          colour="grey10", fill="grey90") +
  geom_sf(data = read_sf("data/ME-GIS/Rivers19.shp"), 
          colour="steelblue", size=0.3) +
  geom_sf(data = read_sf("data/ME-GIS/PrimaryRoads.shp"), 
          size = 0.7, colour="grey30") +
  geom_sf(data = read_sf("data/ME-GIS/Cities.shp")) +
  theme_bw()
```

add city label
```{r}
p + geom_sf_text(data = read_sf("data/ME-GIS/Cities.shp"), aes(label=Name)) + annotation_scale() + annotation_north_arrow(which_north = "true", location = "true", style = north_arrow_nautical())
```

Australia shapefile

```{r}
ozbig <- read_sf("data/gadm36_AUS_shp/gadm36_AUS_1.shp")
oz_st <- maptools::thinnedSpatialPoly(
  as(ozbig, "Spatial"), tolerance = 0.1, 
  minarea = 0.001, topologyPreserve = TRUE)
oz <- st_as_sf(oz_st)
```

```{r}
helper <- function(d){
  group_num <- length(d)
  df <- NULL
  for(i in c(1:group_num)){
    df <- rbind(df, cbind(d[[i]][[1]],
                          rep(i,nrow(d[[i]][[1]])),
                          seq(1:nrow(d[[i]][[1]]))))
                          
  }
  colnames(df) <-c('long','lat','group','order')
  return(as.data.frame(df))
}
library(plyr)
library(ggplot2)
purrr::map(oz$geometry, .f=helper) -> res
purrr::map(res,.f=function(d) ggplot(d)+geom_path(aes(x=long,y=lat,group=group)))
```

```{r}
p = ggplot()
for(i in c(1:length(res))){
  p <- p + geom_path(data=res[[i]],aes(x=long,y=lat,group=group))
}
p
```



